### ISSUE TITLE
在使用updateByPrimaryKeySelective时候抛出了一个乐观锁异常，觉得是你们版本检测有问题，请指教

### ISSUE THREAD

**Issue by liukeling** [open-hand/hzero-starter-parent#4]
在开发中，
supplierReviewRepository.updateByPrimaryKeySelective(review);
（自己的代码）
这行报了错，
org.hzero.core.exception.OptimisticLockException: error.optimistic_lock
	at org.hzero.mybatis.base.impl.BaseRepositoryImpl.checkOptimisticLock(BaseRepositoryImpl.java:241) ~[hzero-starter-mybatis-mapper-1.5.0.RELEASE.jar:1.5.0.RELEASE]
	at org.hzero.mybatis.base.impl.BaseRepositoryImpl.updateByPrimaryKeySelective(BaseRepositoryImpl.java:65) ~[hzero-starter-mybatis-mapper-1.5.0.RELEASE.jar:1.5.0.RELEASE]
场景是我自己本地调试测试的时候，没有修改值，点击保存，然后报了这个错，比较诧异，进去看了下源码发现：
    protected void checkOptimisticLock(int updateCount, Object record) {
        if (updateCount == 0 && record instanceof AuditDomain) {
            throw new OptimisticLockException();
        }
    }
（官方代码）
是这里报的错，然后上层代码是
    public int updateByPrimaryKeySelective(T record) {
        int res = super.updateByPrimaryKeySelective(record);
        this.checkOptimisticLock(res, record);
        this.setObjectVersionNumber(false, record);
        return res;
    }
（官方代码 org.hzero.mybatis.base.impl.BaseRepositoryImpl）
hzero-starter-mybatis-mapper
看代码逻辑是更新条数为0且更新对象AuditDomain这个类型对象则报错
但是，根据方法名，好像是乐观锁检测判断。
乐观锁检测不应该是更新的时候判断更新后与更新前版本号是否一致吗？一致就说明别的事务没有修改，然后就允许提交事务，不一致就说明别的事务有修改该数据，然后才抛出异常，进行回滚吗？为什么这里是根据更新条数来判断？

**Comment by liukeling** [comment]
知道了，那个更新方法是需要设置版本号，更新根据版本号进行更新的
